CREATE TABLE CLIENTES(
       CODIGO              	NUMBER(5,0) NOT NULL,
       NOME                	VARCHAR2(50),
       ENDERECO            	VARCHAR2(50),
       CIDADE              	VARCHAR2(50),
       UF                  	VARCHAR2(20),
       CPF                 	VARCHAR2(11),
       DATA_NASCIMENTO      DATE,
       LIMITE_CREDITO       NUMBER(12,2)
       );
	   
CREATE TABLE ESTADOS(
  UF       		VARCHAR2(2) NOT NULL,
  DESCRICAO   	VARCHAR2(20)
  );
  
ALTER TABLE CLIENTES ADD CONSTRAINT CLIENTES_PK PRIMARY KEY (CODIGO);
ALTER TABLE CLIENTES ADD CONSTRAINT CLIENTES_UF_FK FOREIGN KEY (UF) REFERENCES ESTADOS (UF);
ALTER TABLE ESTADOS ADD CONSTRAINT UF_PK PRIMARY KEY (UF);
  
CREATE SEQUENCE SEQ_CLIENTES

  START WITH 1

  MAXVALUE 99999999

  MINVALUE 1;

